Remove step-oriented build process

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,14 +1,17 @@
 #!/usr/bin/env bash
+set -euo pipefail
+
+NEBULA_TASKS_REPO_BASE="${NEBULA_TASKS_REPO_BASE:-gcr.io/nebula-235818}"
+NEBULA_TASKS_RELEASE_REPOS=( "${NEBULA_TASKS_REPO_BASE}/nebula-workflow-controller" "${NEBULA_TASKS_REPO_BASE}/nebula-metadata-api" )
 
 release_docker_images() {
-    if [ -n "${NEBULA_TASKS_RELEASE_MANIFEST}" ] && [ "${NO_DOCKER_PUSH}" != "yes" ]; then
+    if [ "${NO_DOCKER_PUSH}" != "yes" ]; then
         gcloud auth configure-docker || fail "gcloud authentication was not configured correctly"
 
-        for repo_tag in $(cat "${NEBULA_TASKS_RELEASE_MANIFEST}"); do
-            IFS=':' read -r REPO TAG <<<"${repo_tag}"
-            docker push "${REPO}:${TAG}" || fail "failed to push to the docker repository"
+        for REPO in "${NEBULA_TASKS_RELEASE_REPOS[@]}"; do
+            docker push "${REPO}:${VERSION}" || fail "failed to push to the docker repository"
             if [ "${NEBULA_TASKS_RELEASE_LATEST}" = "true" ]; then
-                docker tag "${REPO}:${TAG}" "${REPO}"
+                docker tag "${REPO}:${VERSION}" "${REPO}"
                 docker push "${REPO}" || fail "failed to push to the docker repository"
             fi
         done
